### ISSUE TITLE
Remove PDF from repository?

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion-manual#2]
`legion.pdf` is included in the repository, but it is 3 years old. Should we either:

 1. Remove `legion.pdf` (so that users aren't confused by a stale PDF)
 2. Start updating `legion.pdf` with every change (requires everyone to remember to rebuild and commit the PDF with every change, or else it gets stale)

**Comment by alexaiken** [comment]
I suggest we get rid of it.  Putting the document on the website makes more sense to me.
________________________________
From: Elliott Slaughter ***@***.***>
Sent: Thursday, September 8, 2022 12:06 PM
To: StanfordLegion/legion-manual ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StanfordLegion/legion-manual] Remove PDF from repository? (Issue #2)


legion.pdf is included in the repository, but it is 3 years old. Should we either:

  1.  Remove legion.pdf (so that users aren't confused by a stale PDF)
  2.  Start updating legion.pdf with every change (requires everyone to remember to rebuild and commit the PDF with every change, or else it gets stale)
